"""Code generation entry point.

Regenerates ``src/tradestation/_generated/`` from ``vendor/swagger.yaml``
(and ``vendor/swagger.v3.json`` when present) using datamodel-code-generator.

See docs/09-codegen-strategy.md for the full codegen strategy.

Usage::

    python scripts/codegen.py
    # or via Makefile:
    make codegen

Steps performed:

1. Verify the pin (vendor/swagger.commit.txt sha256 must match vendor/swagger.yaml).
2. Run datamodel-code-generator with settings from pyproject.toml
   ``[tool.datamodel-codegen]``, writing models.py into the _generated package.
3. Write MANIFEST.txt recording generation metadata.
"""

from __future__ import annotations

import datetime
import hashlib
import importlib.metadata
import re
import subprocess
import sys
from pathlib import Path


def _repo_root() -> Path:
    """Return the repository root (parent of scripts/)."""
    return Path(__file__).resolve().parent.parent


def _compute_sha256(file: Path) -> str:
    h = hashlib.sha256()
    with file.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _read_pin_sha(pin_file: Path) -> str:
    content = pin_file.read_text(encoding="utf-8")
    match = re.search(r"^sha256:\s+([0-9a-f]{64})", content, re.MULTILINE)
    if not match:
        print(f"ERROR: no sha256 line in {pin_file}", file=sys.stderr)
        sys.exit(1)
    return match.group(1)


def _read_pin_commit(pin_file: Path) -> str:
    content = pin_file.read_text(encoding="utf-8")
    match = re.search(r"^commit_sha:\s+(\S+)", content, re.MULTILINE)
    return match.group(1) if match else "unknown"


def _count_operation_ids(swagger_file: Path) -> int:
    """Count operationId occurrences in the swagger file."""
    count = 0
    for line in swagger_file.read_text(encoding="utf-8").splitlines():
        if "operationId:" in line:
            count += 1
    return count


def _count_classes(py_file: Path) -> tuple[int, int]:
    """Return (model_count, enum_count) from a generated .py file."""
    if not py_file.exists():
        return 0, 0
    text = py_file.read_text(encoding="utf-8")
    model_count = len(re.findall(r"^class \w+\((?:BaseModel|RootModel)", text, re.MULTILINE))
    enum_count = len(re.findall(r"^class \w+\((?:Enum|IntEnum|StrEnum)", text, re.MULTILINE))
    return model_count, enum_count


def run_codegen(root: Path, swagger_file: Path, output_dir: Path) -> None:
    """Run datamodel-code-generator and write output to output_dir/models.py."""
    output_file = output_dir / "models.py"

    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(swagger_file),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(output_file),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--field-constraints",
        "--use-annotated",
        "--use-standard-collections",
        "--use-union-operator",
        "--use-double-quotes",
        "--target-python-version",
        "3.10",
        "--snake-case-field",
        "--strict-nullable",
        "--disable-timestamp",
    ]

    print(f"Running datamodel-code-generator → {output_file} ...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR: datamodel-code-generator failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    if result.stderr:
        print(f"WARN: {result.stderr.strip()}", file=sys.stderr)
    print(f"Generated {output_file} ({output_file.stat().st_size} bytes)")


def write_init(output_dir: Path, swagger_file: Path, commit_sha: str) -> None:
    """Write the _generated/__init__.py with a DO NOT EDIT header."""
    source_name = swagger_file.name
    init_text = f"""\
# DO NOT EDIT — generated by scripts/codegen.py
# Source: vendor/{source_name}@{commit_sha}
#
# To regenerate: python scripts/codegen.py
# See docs/09-codegen-strategy.md for the full strategy.

from tradestation._generated import models
from tradestation._generated import operations

__all__ = ["models", "operations"]
"""
    (output_dir / "__init__.py").write_text(init_text, encoding="utf-8")
    print(f"Wrote {output_dir / '__init__.py'}")


def write_manifest(
    output_dir: Path,
    swagger_file: Path,
    commit_sha: str,
    source_sha256: str,
    operations_count: int,
    model_count: int,
    enum_count: int,
) -> None:
    """Write _generated/MANIFEST.txt with generation metadata."""
    try:
        gen_version = importlib.metadata.version("datamodel-code-generator")
    except importlib.metadata.PackageNotFoundError:
        gen_version = "unknown"

    overlay_file = swagger_file.parent / "overlay.yaml"
    overlay_sha = _compute_sha256(overlay_file) if overlay_file.exists() else "none"

    generated_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    manifest = f"""\
generated_at:    {generated_at}
generator:       datamodel-code-generator {gen_version}
source:          vendor/{swagger_file.name}
source_sha:      {commit_sha}
source_sha256:   {source_sha256}
overlay:         vendor/overlay.yaml
overlay_sha256:  {overlay_sha}
operations:      {operations_count}
models:          {model_count}
enums:           {enum_count}
"""
    manifest_file = output_dir / "MANIFEST.txt"
    manifest_file.write_text(manifest, encoding="utf-8")
    print(f"Wrote {manifest_file}")


def main() -> None:
    """Entry point — run codegen pipeline."""
    root = _repo_root()
    swagger_file = root / "vendor" / "swagger.yaml"
    pin_file = root / "vendor" / "swagger.commit.txt"
    output_dir = root / "src" / "tradestation" / "_generated"

    # 1. Verify the pin
    if not swagger_file.exists():
        print(f"ERROR: {swagger_file} not found", file=sys.stderr)
        sys.exit(1)
    if not pin_file.exists():
        print(f"ERROR: {pin_file} not found", file=sys.stderr)
        sys.exit(1)

    expected_sha = _read_pin_sha(pin_file)
    actual_sha = _compute_sha256(swagger_file)
    if actual_sha != expected_sha:
        print(
            f"ERROR: sha256 mismatch for {swagger_file}\n"
            f"  expected: {expected_sha}\n"
            f"  actual:   {actual_sha}",
            file=sys.stderr,
        )
        sys.exit(1)
    print(f"Pin verified: {actual_sha[:12]}...")

    commit_sha = _read_pin_commit(pin_file)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 2. Run datamodel-code-generator
    run_codegen(root, swagger_file, output_dir)

    # 3. Count things for MANIFEST
    models_file = output_dir / "models.py"
    model_count, enum_count = _count_classes(models_file)
    operations_count = _count_operation_ids(swagger_file)

    # 4. Write __init__.py
    write_init(output_dir, swagger_file, commit_sha)

    # 5. Write MANIFEST.txt
    write_manifest(
        output_dir,
        swagger_file,
        commit_sha,
        actual_sha,
        operations_count,
        model_count,
        enum_count,
    )

    print(
        f"\nCodegen complete: {model_count} models, {enum_count} enums, "
        f"{operations_count} operations in swagger."
    )


if __name__ == "__main__":
    main()
